Henrik
Complex-systems-and-devops-gruppe-8/.github pull request #4
Opened 2024-09-23 18:10 UTC by HenrikSkindhoj

2024-09-24 09:00 UTC, christofferfink reviewed
Typescript er ikke et framework, men superset af javascript 

Vite er ikke et framwork men et build tool

2024-09-26 11:39 UTC, christofferfink approved these changes
Ser da nice ud 🤿🏊🏽😎

2024-09-26 12:25 UTC, muItilingualism requested changes
Review

2024-09-26 12:25 UTC, muItilingualism commented on report.md
> +The frontend will be implemented using the JavaScript framework React, paired with Vite as a build tool, and TypeScript, providing a satisfying user experience. The backend will be made with Java/Kot
We dont use kotlin. nor OIDC.

Also, mention maven

2024-09-26 12:25 UTC, muItilingualism commented on report.md
> +This report will go through the design and implementation of the project, as well as how DevOps tools and methods has been applied currently, and how they will be used in the future. The current repo
this aint murica

Change date to be either "22nd of September 2024" or "2024-09-22".

2024-09-26 12:28 UTC, merged